### ISSUE TITLE
It seems like a category for walrus is also needed.

### ISSUE THREAD

**Issue by daoauth** [sui-foundation/awesome-sui#10]
I would like to create and add entries for tools related to walrus.

For example, this is a GitHub Action I developed to make it easier to deploy walrus sites.

https://github.com/zktx-io/walrus-sites-ga
https://github.com/marketplace/actions/walrus-sites-ga
https://github.com/zktx-io/walrus-sites-ga-example

**Comment by hyd628** [comment]
Sounds good. You can go ahead and create the category in a PR and we will merge it. @daoauth

**Comment by daoauth** [comment]
@hyd628 I have added the Walrus category, modified the example.md, and added the Walrus Sites GA to automate the publishing and updating of sites.
