### ISSUE TITLE
Is there a purpose for having a separate page for every tool?

### ISSUE THREAD

**Issue by kkomelin** [sui-foundation/awesome-sui#18]
Thank you for starting this repo!

My first point is that having a separate page for every tool makes the maintenance harder. 
Example: you change something on the frontpage and forget to change the same sentence on the corresponding tool page, so the docs slowly getting out of sync.

Another point against having separate tool pages is that people just need a link to the tool repo to get installation instructions and more up-to-date project information. Human's attention span is decreasing every year - chatgpt and others are giving information quick and people are getting used to it.

I guess you may have or plan to generate a site from/by this repo, then it makes sense. Otherwise, I would discourage you from having to maintain a separate page for every tool.

**Comment by daniellam258** [comment]
Hi @kkomelin ,

The main reason is that some of the tools are unfortunately not very well documented. Therefore, we actually tried out the tools ourselves thoroughly to collect the list of features to provide more information to the audience.

We understand your concern and already had discussion on how to improve this. We will update it soon

**Comment by kkomelin** [comment]
Hi @daniellam258, 
Thank you for explaining the reason to me and discussing the topic internally. I appreciate it. 
You're solving the problem of insufficient documentation, so I think it makes sense total sense. 
I think we may close the issue now. Thanks
